package main

// The pre-M0 differential-baseline gate. M0 rewrites the orchestration around this binary without
// changing the binary's own argv/stdin/stdout/exit-code contract; this file is what proves that
// contract hasn't drifted. Every assertion here failing is a forces_pause condition — `go test`
// returning non-zero is this gate's abort signal, the same convention build-helpers' own exit-code
// contract uses (die(2) for a usage/enumeration error, t.Fatal for its test-time equivalent).
//
// Two independent extractions of the CLI surface, both parsed straight from main.go's source text
// so neither can silently drift from what actually ships:
//   - the dispatch switch in main() (plus the nested switch in runFeedback) — what the binary
//     will actually run for a given argv[0] token;
//   - the usage() heredoc — what the binary tells a caller it supports.
// Both are reconciled against testdata/pre-m0-baseline/surface.json, the committed golden
// enumeration this gate is a differential baseline for. The golden is authored documentation (flag
// requiredness, mutual exclusions, stdin/stdout shape, per-condition exit codes go well beyond what
// either source-level extraction alone can recover), not a byte-for-byte parse of either source —
// so the reconciliation is a set-equality check on command names, never a content diff.
//
// testdata/pre-m0-baseline/help.txt is the literal, byte-for-byte counterpart: the compiled
// binary's own `--help` output, captured verbatim. That one IS a byte-identical capture, and this
// file proves it stays reproducible by invoking the binary twice and diffing both runs against the
// same golden.

import (
	"encoding/json"
	"errors"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
)

const preM0BaselineDir = "testdata/pre-m0-baseline"

// ---- golden fixture shape ----

type baselineCommand struct {
	Name        string            `json:"name"`
	Aliases     []string          `json:"aliases,omitempty"`
	Positionals []map[string]any  `json:"positionals"`
	Flags       []map[string]any  `json:"flags"`
	ExitCodes   map[string]string `json:"exit_codes"`
}

type baselineSurface struct {
	Schema   string            `json:"schema"`
	Commands []baselineCommand `json:"commands"`
}

// loadBaselineSurface reads the committed golden. It never creates or repairs the file — an
// absent or malformed golden is a hard test failure, not a fallback to regenerate one.
func loadBaselineSurface(t *testing.T) baselineSurface {
	t.Helper()
	path := filepath.Join(preM0BaselineDir, "surface.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("pre-M0 baseline golden %s is missing — it must be committed, never regenerated by this test: %v", path, err)
	}
	var s baselineSurface
	if err := json.Unmarshal(raw, &s); err != nil {
		t.Fatalf("pre-M0 baseline golden %s is not valid JSON: %v", path, err)
	}
	if len(s.Commands) == 0 {
		t.Fatalf("pre-M0 baseline golden %s enumerates zero commands", path)
	}
	return s
}

func baselineNames(s baselineSurface) map[string]bool {
	out := make(map[string]bool, len(s.Commands))
	for _, c := range s.Commands {
		out[c.Name] = true
	}
	return out
}

// ---- source-level extraction #1: the dispatch switch ----

// dispatchNames parses the case labels of main()'s top-level switch and runFeedback's nested
// switch directly out of main.go, so a subcommand added to the dispatch table without a matching
// golden entry is caught even if nobody remembered to update usage() too. "-h"/"--help"/"help"
// collapse to the single canonical name "help"; "feedback" itself is never a name in the result —
// it fans out into "feedback add"/"feedback list"/"feedback gate", matching how a caller actually
// invokes it.
func dispatchNames(t *testing.T) map[string]bool {
	t.Helper()
	src := readOwnSource(t, "main.go")

	mainBody, ok := funcBody(src, "func main() {")
	if !ok {
		t.Fatal("could not locate func main() in main.go — dispatch extraction regex is out of sync with the source")
	}
	feedbackBody, ok := funcBody(src, "func runFeedback(rest []string) {")
	if !ok {
		t.Fatal("could not locate func runFeedback in main.go — dispatch extraction regex is out of sync with the source")
	}

	out := map[string]bool{}
	for _, label := range caseLabels(mainBody) {
		switch label {
		case "-h", "--help", "help":
			out["help"] = true
		case "feedback":
			// handled by the nested switch below; the bare dispatch label is not itself a
			// caller-facing command name.
		default:
			out[label] = true
		}
	}
	for _, sub := range caseLabels(feedbackBody) {
		out["feedback "+sub] = true
	}
	return out
}

// funcBody returns the brace-balanced body (including the enclosing braces) of the first function
// whose signature line matches sig exactly, starting from its opening brace.
func funcBody(src, sig string) (string, bool) {
	idx := strings.Index(src, sig)
	if idx < 0 {
		return "", false
	}
	start := idx + strings.Index(src[idx:], "{")
	depth := 0
	for i := start; i < len(src); i++ {
		switch src[i] {
		case '{':
			depth++
		case '}':
			depth--
		}
		if depth == 0 {
			return src[start : i+1], true
		}
	}
	return "", false
}

var quotedRE = regexp.MustCompile(`"([^"]*)"`)

// caseLabels extracts every string literal named by a `case "a", "b":` line within body, in
// source order. A line reading `default:` or any non-case line contributes nothing.
func caseLabels(body string) []string {
	var out []string
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if !strings.HasPrefix(line, "case \"") {
			continue
		}
		for _, m := range quotedRE.FindAllStringSubmatch(line, -1) {
			out = append(out, m[1])
		}
	}
	return out
}

// ---- source-level extraction #2: the usage() heredoc ----

// usageNames parses every "  build-helpers <name> ..." line out of usage()'s raw string literal —
// the same text a caller sees on --help/-h/an unrecognized command. Unlike dispatchNames, this
// extraction has no knowledge of the switch statement at all, so the two can never share a blind
// spot. help/-h/--help document no line of their own (usage() does not describe invoking itself)
// and are intentionally absent from this set; the reconciliation below accounts for that.
func usageNames(t *testing.T) map[string]bool {
	t.Helper()
	src := readOwnSource(t, "main.go")
	body, ok := funcBody(src, "func usage() {")
	if !ok {
		t.Fatal("could not locate func usage() in main.go — usage-text extraction regex is out of sync with the source")
	}
	backtickStart := strings.Index(body, "`")
	backtickEnd := strings.LastIndex(body, "`")
	if backtickStart < 0 || backtickEnd <= backtickStart {
		t.Fatal("could not locate the usage() raw string literal")
	}
	text := body[backtickStart+1 : backtickEnd]

	out := map[string]bool{}
	for _, line := range strings.Split(text, "\n") {
		if !strings.HasPrefix(line, "  build-helpers ") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		name := fields[1]
		if name == "feedback" && len(fields) >= 3 {
			name = "feedback " + fields[2]
		}
		out[name] = true
	}
	if len(out) == 0 {
		t.Fatal("parsed zero command lines out of usage() — extraction regex is out of sync with the source")
	}
	return out
}

func readOwnSource(t *testing.T, path string) string {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("cannot read %s: %v", path, err)
	}
	return string(b)
}

// ---- reconciliation ----

// diffNameSets reports every name present in want but absent from got. A completeness failure is
// exactly a non-empty result here — the same helper backs both the real completeness assertion and
// the planted-omission proof below, so the proof is a real test of the real gate rather than a
// look-alike.
func diffNameSets(want, got map[string]bool) []string {
	var missing []string
	for name := range want {
		if !got[name] {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)
	return missing
}

func TestPreM0Baseline_DispatchAndUsageAgree(t *testing.T) {
	dispatch := dispatchNames(t)
	usage := usageNames(t)

	// usage() documents no line for its own help/-h/--help path — subtract it before comparing.
	dispatchDocumented := map[string]bool{}
	for name := range dispatch {
		if name != "help" {
			dispatchDocumented[name] = true
		}
	}

	if missing := diffNameSets(dispatchDocumented, usage); len(missing) > 0 {
		t.Fatalf("dispatch switch names a command usage() never documents: %v", missing)
	}
	if missing := diffNameSets(usage, dispatchDocumented); len(missing) > 0 {
		t.Fatalf("usage() documents a command the dispatch switch never wires up: %v", missing)
	}
}

func TestPreM0Baseline_GoldenMatchesDispatchAndUsage(t *testing.T) {
	golden := baselineNames(loadBaselineSurface(t))
	dispatch := dispatchNames(t)
	usage := usageNames(t)

	if missing := diffNameSets(dispatch, golden); len(missing) > 0 {
		t.Fatalf("dispatch switch names a command missing from the golden baseline: %v", missing)
	}
	if extra := diffNameSets(golden, dispatch); len(extra) > 0 {
		t.Fatalf("golden baseline documents a command the dispatch switch no longer has: %v", extra)
	}
	for name := range usage {
		if !golden[name] {
			t.Fatalf("usage() names a command missing from the golden baseline: %s", name)
		}
	}
}

// TestPreM0Baseline_BlastRadiusSurfacesCaptureFlagAndExitDetail is AC3: the self-check,
// plan-validation (`validate`), effort-availability (`check-tiers`), and pricing (`record-usage`,
// `attribute`) surfaces must be documented at flag- and exit-code-level granularity, not merely
// listed as present. `validate`/`check-tiers` legitimately take zero flags (single-positional
// commands) — for them, flag-level means the flags array is captured as empty rather than omitted;
// self-check/record-usage/attribute must additionally have a non-empty flags list.
func TestPreM0Baseline_BlastRadiusSurfacesCaptureFlagAndExitDetail(t *testing.T) {
	surface := loadBaselineSurface(t)
	byName := map[string]baselineCommand{}
	for _, c := range surface.Commands {
		byName[c.Name] = c
	}

	mustHaveFlags := map[string]bool{"self-check": true, "record-usage": true, "attribute": true}
	for _, name := range []string{"self-check", "validate", "check-tiers", "record-usage", "attribute"} {
		c, ok := byName[name]
		if !ok {
			t.Fatalf("blast-radius surface %q missing from the golden baseline entirely", name)
		}
		if c.Flags == nil {
			t.Errorf("%s: flags must be captured as an array (empty or populated), not omitted", name)
		}
		if mustHaveFlags[name] && len(c.Flags) == 0 {
			t.Errorf("%s: expected a non-empty flags list, got none", name)
		}
		if len(c.ExitCodes) < 2 {
			t.Errorf("%s: exit_codes must enumerate at least ok + one failure condition, got %d", name, len(c.ExitCodes))
		}
	}
}

// TestPreM0Baseline_PlantedOmissionFailsCompleteness is AC4's proof that the completeness
// assertion actually catches a missing subcommand, without touching the real source or golden: it
// synthesizes a copy of the real dispatch set with one entry deleted and feeds it through the same
// diffNameSets helper TestPreM0Baseline_GoldenMatchesDispatchAndUsage uses for real.
func TestPreM0Baseline_PlantedOmissionFailsCompleteness(t *testing.T) {
	real := dispatchNames(t)
	if !real["validate"] {
		t.Fatal("test setup invalid: 'validate' is not in the real dispatch set")
	}

	mutilated := map[string]bool{}
	for name := range real {
		if name != "validate" {
			mutilated[name] = true
		}
	}

	missing := diffNameSets(real, mutilated)
	if len(missing) != 1 || missing[0] != "validate" {
		t.Fatalf("planted omission of 'validate' was not caught: diffNameSets returned %v", missing)
	}
}

// TestPreM0Baseline_ExtractionIsDeterministic backs AC2 for the source-derived extractions: two
// independent parses of the same unchanged main.go must yield byte-identical results, so the
// completeness check above is a stable gate and not a coin flip.
func TestPreM0Baseline_ExtractionIsDeterministic(t *testing.T) {
	if !reflect.DeepEqual(sortedNames(dispatchNames(t)), sortedNames(dispatchNames(t))) {
		t.Fatal("dispatchNames is not deterministic across repeated runs against the unchanged source")
	}
	if !reflect.DeepEqual(sortedNames(usageNames(t)), sortedNames(usageNames(t))) {
		t.Fatal("usageNames is not deterministic across repeated runs against the unchanged source")
	}
}

func sortedNames(set map[string]bool) []string {
	out := make([]string, 0, len(set))
	for name := range set {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// TestPreM0Baseline_HelpOutputMatchesGoldenByteForByte is the literal byte-for-byte reproducibility
// check (AC2): the compiled binary's --help output, run twice, must be byte-identical to itself AND
// to the committed testdata/pre-m0-baseline/help.txt — never regenerated by this test.
func TestPreM0Baseline_HelpOutputMatchesGoldenByteForByte(t *testing.T) {
	goldenPath := filepath.Join(preM0BaselineDir, "help.txt")
	golden, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("pre-M0 baseline golden %s is missing — it must be committed, never regenerated by this test: %v", goldenPath, err)
	}

	bin := buildCLI(t)
	firstRun := runCLI(t, bin, "--help")
	secondRun := runCLI(t, bin, "--help")

	if !reflect.DeepEqual(firstRun, secondRun) {
		t.Fatal("--help output is not byte-identical across two runs of the same unchanged binary")
	}
	if string(firstRun) != string(golden) {
		t.Fatalf("--help output no longer matches the committed golden byte-for-byte:\n--- got ---\n%s\n--- want ---\n%s", firstRun, golden)
	}
}

// TestPreM0Baseline_BareAndUnknownInvocationExitCodes pins the two usage-error exit paths the
// golden's "help" entry documents (bare invocation vs. an unrecognized command), proven against
// the actual compiled binary rather than main.go's source text.
func TestPreM0Baseline_BareAndUnknownInvocationExitCodes(t *testing.T) {
	bin := buildCLI(t)

	if exitCodeOf(t, bin) == 0 {
		t.Fatal("bare invocation (zero args) must exit non-zero")
	}
	if exitCodeOf(t, bin, "this-command-does-not-exist") == 0 {
		t.Fatal("an unrecognized command must exit non-zero")
	}
}

// exitCodeOf runs bin with args and returns its exit code, tolerating (and expecting) a non-zero
// exit rather than failing the test on one — unlike cli_usage_test.go's runCLI, which is for the
// success-path commands this file otherwise exercises via that same helper.
func exitCodeOf(t *testing.T, bin string, args ...string) int {
	t.Helper()
	cmd := exec.Command(bin, args...)
	err := cmd.Run()
	if err == nil {
		return 0
	}
	var exitErr *exec.ExitError
	if !errors.As(err, &exitErr) {
		t.Fatalf("cmd %v failed to even start: %v", args, err)
	}
	return exitErr.ExitCode()
}
