"""Render each roster-derived output from a loaded roster document.

Every function is pure: roster (+ existing file text, for a patch target) in,
new file text out. The CLI owns all file IO so rendering stays independently
testable and every output comes from the same in-memory roster snapshot —
the one-rendering-pass guarantee.
"""
from __future__ import annotations

import json
import re
from typing import Any

from . import order
from .roster import list_or_contract_output, priced, select

GENERATED_BY = (
    "Generated by roster-gen from the model roster at tag {tag} — "
    "do not hand-edit; edit the roster and regenerate."
)

# Sentinels the plan-schema enum must always carry, independent of what the roster
# currently declares. Checked against this fixed set (not against the roster's own
# `effort_exempt_sentinels`) so a roster edit that drops one is caught here rather
# than silently propagating into a plan-schema enum that can no longer accept it.
REQUIRED_SENTINELS: tuple[str, ...] = ("inherit",)


class NarrowingError(Exception):
    """A generated list would drop an ID the file it replaces already carries."""


def _num(x: float) -> float | int:
    """A price as a bare int when it's whole, else the float — matches the
    on-disk convention in both anthropic-specifications.json copies."""
    return int(x) if float(x).is_integer() else x


def _js_num(x: float) -> str:
    """A price as a JS literal, always with a decimal point — matches
    build-engine.workflow.js's DEFAULT_RATES convention (`25.0`, not `25`)."""
    x = float(x)
    return f"{x:.1f}" if x.is_integer() else str(x)


def _rate_row(table: dict[str, float]) -> dict[str, float | int]:
    """A price table reordered to the on-disk convention: input, cache_write_5m,
    cache_write_1h, cache_read, output."""
    return {k: _num(table[k]) for k in ("input", "cache_write_5m", "cache_write_1h", "cache_read", "output")}


# ---- anthropic-specifications.json (both copies render identically) ----

def render_specs(roster: dict[str, Any], tag: str) -> str:
    models = roster["models"]
    ids = order.capability_order(select(models, lambda r: priced(r) is not None), models)

    model_dim: dict[str, Any] = {}
    pricing_list: dict[str, Any] = {}
    pricing_contract: dict[str, Any] = {}
    for mid in ids:
        row = models[mid]
        model_dim[mid] = {
            "max_output_tokens": row["max_output_tokens"],
            "context_window": row["context_window"],
            "knowledge_cutoff": row["knowledge_cutoff"],
            "min_cacheable_prefix": row["min_cacheable_prefix"],
            "batch_discount": row["batch_discount"],
            "status": row["lifecycle"],
            "deprecation_date": row["deprecation_date"],
        }
        if row["price"]["list"] is not None:
            pricing_list[mid] = _rate_row(row["price"]["list"])
        if row["price"]["contract"] is not None:
            pricing_contract[mid] = _rate_row(row["price"]["contract"])

    doc = {
        "_schema_version": 1,
        "_generated_by": GENERATED_BY.format(tag=tag),
        "_comment": (
            "Canonical per-model rate + limit table for build-with-team. Dimension-selectable "
            "shape: top-level `model` and `pricing` dims; a consumer prefers a model's "
            "`pricing.contract` entry over `pricing.list` when present."
        ),
        "_source": roster["_source"],
        "_unit": roster["_unit"],
        "_as_of": roster["_as_of"],
        "model": model_dim,
        "pricing": {"list": pricing_list, "contract": pricing_contract},
    }
    return json.dumps(doc, indent=2, ensure_ascii=True) + "\n"


# ---- plan-schema.json: only $defs.task.properties.model is roster-derived ----

def patch_plan_schema(existing_text: str, roster: dict[str, Any], tag: str) -> str:
    doc = json.loads(existing_text)
    models = roster["models"]
    sentinels = list(roster["effort_exempt_sentinels"])

    new_work = select(models, lambda r: r["selectable"] == "new-work")
    enum = order.sequence(new_work, order.PLAN_ENUM_ORDER) + sentinels
    missing = [s for s in REQUIRED_SENTINELS if s not in enum]
    if missing:
        raise ValueError(f"generated plan-schema enum is missing required sentinel(s): {missing}")

    model_prop = doc["$defs"]["task"]["properties"]["model"]
    model_prop["enum"] = enum
    model_prop["description"] = (
        "Pinned full model ID for the software-engineer on this task, chosen per governance-model-tiering."
    )
    model_prop["$comment"] = (
        GENERATED_BY.format(tag=tag)
        + " Every selectable=='new-work' roster row (fixed display order), plus the roster's effort_exempt_sentinels."
    )
    return json.dumps(doc, indent=2, ensure_ascii=True) + "\n"


# ---- build-engine.workflow.js: only the DEFAULT_RATES const is roster-derived ----

_JS_BLOCK_RE = re.compile(
    r"(?:[ \t]*// >>> roster-gen:generated \(tag=[^)]*\)[^\n]*\n)?"
    r"const DEFAULT_RATES = \{.*?\}\n"
    r"(?:[ \t]*// <<< roster-gen:generated <<<\n)?",
    re.DOTALL,
)


def patch_build_engine(existing_text: str, roster: dict[str, Any], tag: str) -> str:
    models = roster["models"]
    ids = order.capability_order(select(models, lambda r: priced(r) is not None), models)

    pairs = [f"'{mid}': {_js_num(list_or_contract_output(models[mid]))}" for mid in ids]
    rows = [", ".join(pairs[i : i + 4]) + "," for i in range(0, len(pairs), 4)]
    body = "\n  ".join(rows)
    block = (
        f"// >>> roster-gen:generated (tag={tag}) — do not hand-edit this block; edit the roster and regenerate <<<\n"
        f"const DEFAULT_RATES = {{\n  {body}\n}}\n"
        f"// <<< roster-gen:generated <<<\n"
    )
    new_text, count = _JS_BLOCK_RE.subn(block, existing_text, count=1)
    if count != 1:
        raise ValueError("could not locate the DEFAULT_RATES block in build-engine.workflow.js")
    return new_text


# ---- hooks/model-roster: the model-gate's allowlist (whole file) ----

def render_gate_allowlist(roster: dict[str, Any], tag: str, existing_ids: set[str] | None = None) -> str:
    models = roster["models"]
    ids = select(models, lambda r: r["selectable"] != "retired")
    if existing_ids is not None:
        dropped = existing_ids - set(ids)
        if dropped:
            raise NarrowingError(
                f"generated gate allowlist would drop already-allowed ID(s): {sorted(dropped)}"
            )
    ordered = order.sequence(ids, order.GATE_ALLOWLIST_ORDER)
    header = [
        "# Pinned full model IDs — the model-allowlist gate's roster.",
        f"# {GENERATED_BY.format(tag=tag)}",
        "# This is governance-sub-agents' own tiering-authority roster, kept in sync with",
        "# the ID enumeration in governance-model-tiering.md (a sync test asserts they match).",
        "# It is a SUPERSET of plan-schema's model enum: it keeps every selectable ==",
        "# legacy-pin-only ID that the plan schema omits, and excludes the schema's `inherit`",
        "# sentinel. One full ID per line; blank lines and `#` comments ignored. A trailing",
        "# [1m] window selector is accepted by the gate against the bare ID here.",
    ]
    return "\n".join(header + ordered) + "\n"


# ---- governance-model-tiering.md: only the capability snapshot table is roster-derived ----

_MD_GENERATED_RE = re.compile(
    r"<!-- roster-gen:generated \(tag=[^)]*\)[^\n]*-->\n"
    r".*?"
    r"<!-- roster-gen:end -->\n",
    re.DOTALL,
)
_MD_BOOTSTRAP_RE = re.compile(
    r"\| Model \| Capability anchor.*?\n\|---(?:\|---)*\|\n(?:\|.*?\n)+",
    re.DOTALL,
)


def _capability_table(roster: dict[str, Any], tag: str) -> str:
    models = roster["models"]
    ids = order.capability_order(select(models, lambda r: r["selectable"] != "retired"), models)
    rows = [
        "| Model | Selectable | Context window | Max output | Price $/Mtok (in / out) | Effort available |",
        "|---|---|---|---|---|---|",
    ]
    for mid in ids:
        row = models[mid]
        price = priced(row)
        price_cell = f"${price['input']:g} / ${price['output']:g}" if price else "n/a"
        ctx = row["context_window"] if row["context_window"] is not None else "n/a"
        out = row["max_output_tokens"] if row["max_output_tokens"] is not None else "n/a"
        effort = ", ".join(row["effort_available"]) if row["effort_available"] else "n/a"
        if row["effort_exempt"]:
            effort += " (exempt)"
        rows.append(f"| `{mid}` | {row['selectable']} | {ctx} | {out} | {price_cell} | {effort} |")
    return "\n".join(rows) + "\n"


def patch_tiering_doc(existing_text: str, roster: dict[str, Any], tag: str) -> str:
    block = (
        f"<!-- roster-gen:generated (tag={tag}) — do not hand-edit; edit the roster and regenerate -->\n"
        f"{_capability_table(roster, tag)}"
        f"<!-- roster-gen:end -->\n"
    )
    new_text, count = _MD_GENERATED_RE.subn(block, existing_text, count=1)
    if count == 1:
        return new_text
    new_text, count = _MD_BOOTSTRAP_RE.subn(block, existing_text, count=1)
    if count != 1:
        raise ValueError("could not locate the capability snapshot table in governance-model-tiering.md")
    return new_text
