package toolchain

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/johnrichter/claude-shared-tooling/go/jsondoc"
	"github.com/johnrichter/claude-shared-tooling/go/state"
)

// cacheSchemaVersion is the on-disk cache document's schema version (see
// go/state for the store this rides on).
const cacheSchemaVersion = 1

// cacheFileName is the cache document's name inside a caller's CacheDir.
const cacheFileName = "toolchain-cache.json"

// buildOutputDirs are directories ContentHash never descends into: their
// contents are generated by the very tool being cached, or are VCS/tool
// internals — never part of a target's own spec-bearing input, and hashing
// them would make a run's own output invalidate its own cache entry.
var buildOutputDirs = map[string]bool{
	".git": true, "target": true, "node_modules": true,
	"dist": true, "build": true, "__pycache__": true, ".venv": true,
}

// ContentHash returns a deterministic digest of every regular file under
// dir, excluding buildOutputDirs. Two directory trees with the same file
// paths and byte contents hash identically regardless of walk order,
// timestamps, or permissions, so the cache below can tell "the target
// actually changed" apart from "it was only touched".
func ContentHash(dir string) (string, error) {
	manifest := map[string]string{}
	err := filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			if path != dir && buildOutputDirs[d.Name()] {
				return filepath.SkipDir
			}
			return nil
		}
		rel, err := filepath.Rel(dir, path)
		if err != nil {
			return err
		}
		b, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		sum := sha256.Sum256(b)
		manifest[filepath.ToSlash(rel)] = hex.EncodeToString(sum[:])
		return nil
	})
	if err != nil {
		return "", fmt.Errorf("toolchain: hash %s: %w", dir, err)
	}
	hash, err := jsondoc.ContentHash(manifest)
	if err != nil {
		return "", fmt.Errorf("toolchain: canonicalize hash manifest for %s: %w", dir, err)
	}
	return hash, nil
}

// cachePath returns the cache document's path inside cacheDir.
func cachePath(cacheDir string) string {
	return filepath.Join(cacheDir, cacheFileName)
}

// lookupCache returns the RunResult recorded for id the last time its
// target's content hash was contentHash, and true — Level-0 impact-skip: a
// hit means the target has not changed since that run, so it never needs
// re-executing. A missing entry, a hash mismatch, or an unreadable cache
// document are all reported as a plain miss (false, nil error) — a corrupt
// or absent cache must never block a run, only cost it a skip it could have
// had.
//
// allowWarnings must also match the recorded run's: the same content can
// classify differently under a different must-fail-on-warning policy, so a
// replayed verdict is only valid for the policy it was produced under. A
// policy change is a miss, forcing a fresh run that reclassifies.
func lookupCache(cacheDir, id, contentHash string, allowWarnings bool) (RunResult, bool, error) {
	doc, err := state.Read(cachePath(cacheDir), cacheSchemaVersion, nil)
	if err != nil {
		return RunResult{}, false, nil
	}
	targets, _ := doc["targets"].(map[string]any)
	raw, ok := targets[id]
	if !ok {
		return RunResult{}, false, nil
	}
	entry, ok := raw.(map[string]any)
	if !ok || entry["content_hash"] != contentHash || entry["allow_warnings"] != allowWarnings {
		return RunResult{}, false, nil
	}
	encoded, err := json.Marshal(entry["result"])
	if err != nil {
		return RunResult{}, false, nil
	}
	var rr RunResult
	if err := json.Unmarshal(encoded, &rr); err != nil {
		return RunResult{}, false, nil
	}
	return rr, true, nil
}

// saveCache records result under id, keyed to contentHash and the
// allowWarnings policy it was classified under, so a future call with an
// unchanged target and the same policy can be served from lookupCache
// instead of re-running the tool. Concurrent callers serialize through
// state.WithLock so two runs racing the same cache document never lose one's
// write.
func saveCache(cacheDir, id, contentHash string, allowWarnings bool, result RunResult) error {
	if err := os.MkdirAll(cacheDir, 0o755); err != nil {
		return fmt.Errorf("toolchain: create cache dir %s: %w", cacheDir, err)
	}
	path := cachePath(cacheDir)
	return state.WithLock(path, func() error {
		doc, err := state.Read(path, cacheSchemaVersion, nil)
		if err != nil {
			return fmt.Errorf("toolchain: read cache %s: %w", path, err)
		}
		targets, _ := doc["targets"].(map[string]any)
		if targets == nil {
			targets = map[string]any{}
		}
		targets[id] = map[string]any{"content_hash": contentHash, "allow_warnings": allowWarnings, "result": result}
		doc["targets"] = targets
		if err := state.Write(path, doc, 0o644); err != nil {
			return fmt.Errorf("toolchain: write cache %s: %w", path, err)
		}
		return nil
	})
}
