//! `M2.P2.T2` -- the one-time SC6' cutover no-regression gate. Proves the
//! Rust validator (`frontmatter::validate`) reproduces the CURRENT Python
//! frontmatter gate's verdicts (`audit_helper.frontmatter.validate`) over a
//! frozen, committed fixture corpus. Retires once the Python gate is
//! deleted (`M2.P2.T3`) -- this is a migration gate, not a maintained
//! parity net.
//!
//! The golden this test reads (`cutover/expected_verdicts.json`) is
//! produced only by the committed `cutover/capture_python_verdicts.py`,
//! run against the live Python oracle. This test NEVER regenerates it --
//! an absent golden is a hard failure with a message pointing at the
//! capture script, not a silent skip or a self-authored baseline.
//!
//! # Normalization (the only deltas allowed before a direct compare)
//! Three approved deltas from `schemas/frontmatter/DIVERGENCES.md`,
//! applied before comparing a fixture's Rust and Python violation lists:
//!   - **D1** -- drop any Rust violation whose `field` is `"owner"`. The
//!     psa-apm pack adds `owner` as a fourth singleton namespace; the
//!     Python gate (`schema.py`) never enforced it.
//!   - **Python-only codes** -- drop any Python golden violation whose
//!     `code` is `DESCRIPTION_INVALID_SCALAR` or `INVALID_UPDATED_FORMAT`.
//!     Both are out of scope for the Rust validator (see `validate.rs`'s
//!     module doc).
//!   - **Parse-layer codes** -- `MISSING_FRONTMATTER`/`MALFORMED_FRONTMATTER`
//!     are Python violations but a Rust `parse()` `Result`; fixtures that
//!     trigger them live in a separate group (below) with a parse-layer
//!     assertion instead of a violation-list compare.
//!
//! Everything else is a faithful port and is compared directly, including
//! message text.

use frontmatter::{parse, validate, Profile};
use serde::Deserialize;
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct ManifestEntry {
    fixture: String,
    rel_path: String,
    group: String,
}

#[derive(Deserialize)]
struct GoldenEntry {
    file_class: String,
    is_valid: bool,
    violations: Vec<GoldenViolation>,
}

#[derive(Deserialize)]
struct GoldenViolation {
    code: String,
    field: Option<String>,
    message: String,
}

/// Python-only violation codes (out of scope for the Rust validator; see
/// the module doc's normalization list) -- dropped from the golden side
/// before comparing.
const PYTHON_ONLY_CODES: [&str; 2] = ["DESCRIPTION_INVALID_SCALAR", "INVALID_UPDATED_FORMAT"];

fn cutover_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/cutover")
}

fn load_manifest() -> Vec<ManifestEntry> {
    let path = cutover_dir().join("manifest.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cutover manifest missing at {}: {e}", path.display()));
    serde_json::from_str(&text).expect("cutover manifest is not valid JSON")
}

/// Loads the committed golden. Fails loudly, rather than regenerating one,
/// when it is absent -- see this module's doc comment.
fn load_golden() -> HashMap<String, GoldenEntry> {
    let path = cutover_dir().join("expected_verdicts.json");
    let text = fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "cutover golden missing at {}: {e}\n\
             this golden is produced by tests/cutover/capture_python_verdicts.py \
             run against the audit-helper venv -- it is never generated by cargo test",
            path.display()
        )
    });
    serde_json::from_str(&text).expect("cutover golden is not valid JSON")
}

fn read_fixture(fixture: &str) -> String {
    let path = cutover_dir().join("fixtures").join(fixture);
    fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cutover fixture missing at {}: {e}", path.display()))
}

/// Rust violations with D1's `owner` divergence filtered out.
fn normalized_rust(violations: &[frontmatter::Violation]) -> Vec<(&str, &str, &str)> {
    violations
        .iter()
        .filter(|v| v.field != "owner")
        .map(|v| (v.code.as_str(), v.field.as_str(), v.message.as_str()))
        .collect()
}

/// Golden violations with the two Python-only codes filtered out.
fn normalized_golden(violations: &[GoldenViolation]) -> Vec<(&str, &str, &str)> {
    violations
        .iter()
        .filter(|v| !PYTHON_ONLY_CODES.contains(&v.code.as_str()))
        .map(|v| {
            (
                v.code.as_str(),
                v.field.as_deref().unwrap_or(""),
                v.message.as_str(),
            )
        })
        .collect()
}

/// Unit-level coverage on `normalized_rust`/`normalized_golden` themselves:
/// each drop is CODE-scoped, not whole-entry-scoped. A fixture-level compare
/// can't tell "dropped the whole entry" apart from "dropped one violation
/// and kept the rest" when the dropped code happens to be the only one
/// present -- these tests use synthetic mixed lists (not producible by the
/// current Rust validator, since it doesn't emit the Python-only codes) to
/// force that distinction.
#[cfg(test)]
mod normalization_is_code_scoped {
    use super::*;

    /// D1: filtering `owner` out of a Rust violation list must remove ONLY
    /// the owner entry, leaving a co-occurring real violation on the same
    /// file intact and still subject to comparison.
    #[test]
    fn owner_filter_drops_only_the_owner_entry_not_the_whole_list() {
        let violations = vec![
            frontmatter::Violation {
                code: "MISSING_REQUIRED_TAG".to_string(),
                field: "owner".to_string(),
                message: "missing required 'owner:' tag".to_string(),
            },
            frontmatter::Violation {
                code: "MISSING_REQUIRED_TAG".to_string(),
                field: "type".to_string(),
                message: "missing required 'type:' tag".to_string(),
            },
        ];

        let result = normalized_rust(&violations);

        assert_eq!(
            result,
            vec![(
                "MISSING_REQUIRED_TAG",
                "type",
                "missing required 'type:' tag"
            )],
            "the owner entry must be dropped and the type entry must survive untouched"
        );
    }

    /// Python-only-code filter: dropping `DESCRIPTION_INVALID_SCALAR` (a
    /// code out of the Rust validator's scope, per DIVERGENCES.md) from a
    /// golden violation list must remove ONLY that entry, leaving the
    /// bracketing real violations on either side of it intact.
    #[test]
    fn python_only_code_filter_drops_only_the_matching_entry() {
        let violations = vec![
            GoldenViolation {
                code: "MISSING_REQUIRED_FIELD".to_string(),
                field: Some("links".to_string()),
                message: "required field 'links:' is missing".to_string(),
            },
            GoldenViolation {
                code: "DESCRIPTION_INVALID_SCALAR".to_string(),
                field: Some("description".to_string()),
                message: "description must be a quoted scalar".to_string(),
            },
            GoldenViolation {
                code: "MISSING_REQUIRED_TAG".to_string(),
                field: Some("type".to_string()),
                message: "missing required 'type:' tag".to_string(),
            },
        ];

        let result = normalized_golden(&violations);

        assert_eq!(
            result,
            vec![
                (
                    "MISSING_REQUIRED_FIELD",
                    "links",
                    "required field 'links:' is missing"
                ),
                (
                    "MISSING_REQUIRED_TAG",
                    "type",
                    "missing required 'type:' tag"
                ),
            ],
            "only the middle (DESCRIPTION_INVALID_SCALAR) entry must be dropped; \
             the bracketing real violations must survive in their original order"
        );
    }

    /// Same as above for the other Python-only code, `INVALID_UPDATED_FORMAT`,
    /// confirming both entries in `PYTHON_ONLY_CODES` are independently
    /// code-scoped rather than one being an accidental whole-list clear.
    #[test]
    fn invalid_updated_format_filter_drops_only_the_matching_entry() {
        let violations = vec![
            GoldenViolation {
                code: "INVALID_UPDATED_FORMAT".to_string(),
                field: Some("updated".to_string()),
                message: "'updated:' is not a valid ISO 8601 timestamp".to_string(),
            },
            GoldenViolation {
                code: "MISSING_REQUIRED_TAG".to_string(),
                field: Some("privacy".to_string()),
                message: "missing required 'privacy:' tag".to_string(),
            },
        ];

        let result = normalized_golden(&violations);

        assert_eq!(
            result,
            vec![(
                "MISSING_REQUIRED_TAG",
                "privacy",
                "missing required 'privacy:' tag"
            )],
            "INVALID_UPDATED_FORMAT must be dropped independently of DESCRIPTION_INVALID_SCALAR"
        );
    }
}

#[test]
fn well_formed_fixtures_reproduce_the_python_golden() {
    let pack_json = frontmatter::embedded_pack_json("psa-apm@1").expect("psa-apm@1 must resolve");
    let profile = Profile::from_json(frontmatter::embedded_core_json(), pack_json)
        .expect("embedded core + psa-apm@1 pack must build a Profile");
    let golden = load_golden();
    let manifest = load_manifest();

    let mut checked = 0;
    for entry in manifest.iter().filter(|e| e.group == "well_formed") {
        let text = read_fixture(&entry.fixture);
        let parsed = parse(&text).unwrap_or_else(|e| {
            panic!(
                "fixture {} is in the well_formed group but failed to parse: {e:?}",
                entry.fixture
            )
        });
        let rust_entry = validate(&parsed, &entry.rel_path, &profile);

        let golden_entry = golden.get(&entry.rel_path).unwrap_or_else(|| {
            panic!(
                "no golden entry for {} (fixture {}) -- re-run capture_python_verdicts.py",
                entry.rel_path, entry.fixture
            )
        });

        let rust_violations = normalized_rust(&rust_entry.violations);
        let golden_violations = normalized_golden(&golden_entry.violations);

        assert_eq!(
            rust_violations, golden_violations,
            "violation mismatch for {} (fixture {})",
            entry.rel_path, entry.fixture
        );
        assert_eq!(
            rust_entry.file_class, golden_entry.file_class,
            "file_class mismatch for {} (fixture {})",
            entry.rel_path, entry.fixture
        );
        assert_eq!(
            golden_violations.is_empty(),
            golden_entry.is_valid,
            "golden is_valid at {} doesn't match its own (normalized) violation list -- \
             capture script or golden is stale",
            entry.rel_path
        );
        assert_eq!(
            rust_violations.is_empty(),
            golden_violations.is_empty(),
            "is_valid mismatch (post-normalization) for {} (fixture {})",
            entry.rel_path,
            entry.fixture
        );

        checked += 1;
    }

    assert!(
        checked > 0,
        "no well_formed fixtures found -- manifest.json is empty or miscategorized"
    );
}

/// The malformed/absent-frontmatter fixtures. Python models these as
/// `MISSING_FRONTMATTER`/`MALFORMED_FRONTMATTER` violations from
/// `validate()`; the Rust crate models the same input shapes one layer
/// earlier, in `parse()`'s `Result` -- so this group is asserted at that
/// layer instead of joining the shared-vocabulary violation compare above.
#[test]
fn parse_error_fixtures_are_rejected_or_treated_as_missing_at_the_parse_layer() {
    let manifest = load_manifest();
    let mut checked = 0;

    for entry in manifest.iter().filter(|e| e.group == "parse_error") {
        let text = read_fixture(&entry.fixture);
        match entry.fixture.as_str() {
            "malformed_yaml.md" => {
                let err = parse(&text).expect_err(&format!(
                    "{} is expected to fail to parse (malformed YAML)",
                    entry.fixture
                ));
                assert!(
                    matches!(err, frontmatter::FrontmatterParseError::MalformedYaml(_)),
                    "expected MalformedYaml for {}, got {err:?}",
                    entry.fixture
                );
            }
            "no_frontmatter.md" => {
                let parsed = parse(&text).unwrap_or_else(|e| {
                    panic!("{} is expected to parse as body-only: {e:?}", entry.fixture)
                });
                assert!(
                    parsed.raw_fields.is_empty(),
                    "{} is expected to have no frontmatter fields at all",
                    entry.fixture
                );
            }
            other => panic!("unrecognized parse_error fixture {other}; add a case above"),
        }
        checked += 1;
    }

    assert!(
        checked > 0,
        "no parse_error fixtures found -- manifest.json is empty or miscategorized"
    );
}
