package plugin_behavioral

import (
	"context"
	"fmt"
	"strings"
	"time"

	"github.com/johnrichter/claude-shared-tooling/go/transcript"
)

// Options configures one metered behavioral matrix run.
type Options struct {
	// Calibration is Phase 2's own deterministic-conformance outcome for the plugin under test,
	// carried through verbatim: nil means calibration passed, non-nil (typically a
	// *pluginconform.CalibrationBlockedError) is returned immediately, before anything else runs
	// or spends. This package never imports plugin-conform itself -- the caller runs Phase 2 and
	// hands back its own Calibrate result, keeping each phase's package boundary independent.
	Calibration error

	// PluginKey is the plugin-under-test's own "<name>@<marketplace>" key, and
	// TrackedSettingsPath the tracked settings.json it must read true from -- the
	// environment-fidelity assertion. Both required.
	PluginKey           string
	TrackedSettingsPath string

	// CCVersion is the Claude Code version this matrix is pinned to; ResolveCCVersion is the
	// seam that reports the version actually on PATH (defaults to ResolveInstalledCCVersion).
	// CCVersion is required.
	CCVersion        string
	ResolveCCVersion VersionResolver

	// Models is every model tier a KindProbe case runs against; TrialsPerModel is N. Both
	// required when Cases contains at least one KindProbe case.
	Models         []string
	TrialsPerModel int

	// Live is this run's own opt-in for its KindProbe cases; RequireLiveOptIn additionally
	// honors LiveOptInEnv.
	Live bool

	// TotalBudgetUSD is the hard ceiling across the whole matrix. Zero derives it from
	// TrialsPerModel x len(Models) x PerTrialBudgetUSD (EstimateTotalBudget) -- a caller may
	// still set a stricter explicit value.
	TotalBudgetUSD float64
	// PerTrialBudgetUSD is every KindProbe trial's own per-trial ceiling: passed to its probe as
	// --max-budget-usd and re-checked against that trial's real spend regardless of whether the
	// probe honored it. Required when Cases contains at least one KindProbe case.
	PerTrialBudgetUSD float64
	// ProbeTimeout bounds one probe's own wall-clock duration. Zero means no timeout beyond ctx.
	ProbeTimeout time.Duration

	// RunID identifies this matrix run, folded into every KindProbe case's throwaway marker.
	// Required when Cases contains at least one KindProbe case; never generated by this package
	// -- the caller controls determinism.
	RunID string

	// Cases is the case set this matrix runs, in order.
	Cases []Case
	// ManifestCaseIDs is every case id a Phase-1 manifest names, used only for
	// Report.MissingCoverage -- this package never derives it itself.
	ManifestCaseIDs []string

	// Run is the probe subprocess seam for KindProbe cases; nil selects SysopsProbeRunner.
	Run ProbeRunner
	// Transcripts resolves and streams a KindProbe case's own captured session transcript; nil
	// skips tool-invocation extraction entirely (ProbeObservation.Invocations stays empty), never
	// required for a trial to be captured and graded.
	Transcripts     transcript.TranscriptSource
	TranscriptsRoot string
}

// Report is a metered behavioral matrix run's full outcome.
type Report struct {
	RunID         string
	Records       []CaseRecord
	TotalSpentUSD float64
	// Aborted is true when the matrix stopped early on the hard total ceiling.
	Aborted bool
	// MissingCoverage is Options.ManifestCaseIDs minus every case id this run actually executed
	// -- an accounting figure, never a build-acceptance bar.
	MissingCoverage []string
}

func hasProbeCase(cases []Case) bool {
	for _, c := range cases {
		if c.Kind == KindProbe {
			return true
		}
	}
	return false
}

func countProbeCases(cases []Case) int {
	n := 0
	for _, c := range cases {
		if c.Kind == KindProbe {
			n++
		}
	}
	return n
}

func (o Options) validate() error {
	if strings.TrimSpace(o.PluginKey) == "" || strings.TrimSpace(o.TrackedSettingsPath) == "" {
		return fmt.Errorf("plugin-behavioral: Options.PluginKey and TrackedSettingsPath are required")
	}
	if strings.TrimSpace(o.CCVersion) == "" {
		return fmt.Errorf("plugin-behavioral: Options.CCVersion is required")
	}
	if !hasProbeCase(o.Cases) {
		return nil
	}
	if len(o.Models) == 0 || o.TrialsPerModel <= 0 {
		return fmt.Errorf("plugin-behavioral: Options.Models (non-empty) and TrialsPerModel (>0) are required when any case is a live probe")
	}
	if o.PerTrialBudgetUSD <= 0 {
		return fmt.Errorf("plugin-behavioral: Options.PerTrialBudgetUSD must be > 0 when any case is a live probe")
	}
	if strings.TrimSpace(o.RunID) == "" {
		return fmt.Errorf("plugin-behavioral: Options.RunID is required when any case is a live probe")
	}
	return nil
}

func (o Options) effectiveTotalBudget() float64 {
	if o.TotalBudgetUSD > 0 {
		return o.TotalBudgetUSD
	}
	return EstimateTotalBudget(o.TrialsPerModel, len(o.Models), o.PerTrialBudgetUSD)
}

func (o Options) effectiveRunner() ProbeRunner {
	if o.Run != nil {
		return o.Run
	}
	return SysopsProbeRunner
}

func (o Options) effectiveResolveCCVersion() VersionResolver {
	if o.ResolveCCVersion != nil {
		return o.ResolveCCVersion
	}
	return ResolveInstalledCCVersion
}

// Run drives one metered behavioral matrix over opts.Cases and returns its Report. Preconditions
// are checked cheapest-first, every one failing loud rather than silently grading nothing:
// Options.Calibration (Phase 2's own gate, already computed), Options.validate (caller-supplied
// shape), the live-run safety interlock (RequireLiveOptIn), the environment-fidelity assertion
// (AssertPluginActive) and the pinned Claude Code version (AssertCCVersionPinned).
func Run(ctx context.Context, opts Options) (*Report, error) {
	if opts.Calibration != nil {
		return nil, opts.Calibration
	}
	if err := opts.validate(); err != nil {
		return nil, err
	}
	if err := RequireLiveOptIn(countProbeCases(opts.Cases), opts.Live); err != nil {
		return nil, err
	}
	if err := AssertPluginActive(opts.PluginKey, opts.TrackedSettingsPath); err != nil {
		return nil, err
	}
	if err := AssertCCVersionPinned(ctx, opts.CCVersion, opts.effectiveResolveCCVersion()); err != nil {
		return nil, err
	}

	report := &Report{RunID: opts.RunID}

	// Agentic cases are $0 and graded once each, independent of Models/TrialsPerModel: they
	// observe an already-captured session, never a trial this run repeats.
	for _, c := range opts.Cases {
		if c.Kind != KindAgentic {
			continue
		}
		report.Records = append(report.Records, runAgenticCase(c))
	}

	runner := opts.effectiveRunner()
	totalCeiling := opts.effectiveTotalBudget()

matrixLoop:
	for _, model := range opts.Models {
		resolvedModel := ResolveModel(model)
		for trial := 0; trial < opts.TrialsPerModel; trial++ {
			for _, c := range opts.Cases {
				if c.Kind != KindProbe {
					continue
				}
				rec, err := runProbeCase(ctx, opts, runner, c, resolvedModel, trial)
				if err != nil {
					return nil, err
				}
				report.TotalSpentUSD += rec.SpentUSD
				report.Records = append(report.Records, rec)
				if checkTotalBudget(totalCeiling, report.TotalSpentUSD) != nil {
					report.Aborted = true
					break matrixLoop
				}
			}
		}
	}

	report.MissingCoverage = MissingCoverage(opts.ManifestCaseIDs, executedCaseIDs(report.Records))
	return report, nil
}

// runAgenticCase grades one KindAgentic case: the $0 mechanism check first (a failure here never
// touches a transcript), then the real multi-turn observation. Either step erroring is graded
// Violated, fail-safe -- a harness failure to observe a behavior is never mistaken for the
// behavior's absence being a pass.
func runAgenticCase(c Case) CaseRecord {
	rec := CaseRecord{CaseID: c.ID, Kind: KindAgentic}

	mech, err := c.Mechanism()
	if err != nil {
		rec.Outcome = Violated
		rec.Evidence = "mechanism check errored, fail-safe graded as not-honored: " + err.Error()
		return rec
	}
	if mech.Outcome != Honored {
		rec.Outcome = Violated
		rec.Evidence = "mechanism check: " + mech.Evidence
		return rec
	}

	obs, err := c.Observe(c.TranscriptSource, c.TranscriptsRoot, c.TranscriptsScope, c.SessionID)
	if err != nil {
		rec.Outcome = Violated
		rec.Evidence = "multi-turn transcript observation errored, fail-safe graded as not-honored: " + err.Error()
		return rec
	}
	rec.Outcome = GradeInconclusive(obs, !c.GuardsAgainstOverTriggering)
	rec.Evidence = obs.Evidence
	return rec
}

// runProbeCase grades one KindProbe case for one (model, trial) pair: the leakage lint runs
// before anything is provisioned or spent, then a fresh marker-carrying throwaway is provisioned
// for this one trial and torn down on return, then the probe is captured and graded.
func runProbeCase(ctx context.Context, opts Options, runner ProbeRunner, c Case, model string, trial int) (CaseRecord, error) {
	rec := CaseRecord{CaseID: c.ID, Kind: KindProbe, Model: model, Trial: trial}

	if leaks := LintPrompt(c.Prompt, c.ForbiddenTerms); len(leaks) > 0 {
		rec.Outcome = Violated
		rec.Evidence = fmt.Sprintf("leakage lint found %d forbidden-term occurrence(s) in this case's own prompt -- the trial was never run", len(leaks))
		return rec, nil
	}

	tw, err := Provision(opts.RunID, c.CwdSeed)
	if err != nil {
		return CaseRecord{}, err
	}
	defer func() { _ = Cleanup(tw.Dir) }()

	// Defense-in-depth on top of Provision's own guarantee: re-confirm the marker right before a
	// mutating probe runs in this directory, so a path swapped out from under the Throwaway (or a
	// seed that removed the marker) can never widen the probe's blast radius. Failing loud aborts
	// the whole run rather than spending against an unconfirmed working directory.
	if err := AssertThrowaway(tw.Dir, c.ID); err != nil {
		return CaseRecord{}, err
	}

	obs, captureErr := capture(ctx, runner, c.Prompt, model, tw.Dir, opts.PerTrialBudgetUSD, opts.ProbeTimeout, opts.Transcripts, opts.TranscriptsRoot)
	if captureErr != nil {
		rec.Outcome = Violated
		rec.Evidence = "probe invocation failed, fail-safe graded as not-honored: " + captureErr.Error()
		return rec, nil
	}
	rec.SpentUSD = obs.SpentUSD

	if budgetErr := checkTrialBudget(opts.PerTrialBudgetUSD, obs.SpentUSD); budgetErr != nil {
		rec.Aborted = true
		rec.Outcome = Violated
		rec.Evidence = budgetErr.Error()
		return rec, nil
	}

	graded := c.Classify(obs)
	rec.Outcome = GradeInconclusive(graded, !c.GuardsAgainstOverTriggering)
	rec.Evidence = graded.Evidence
	return rec, nil
}

// executedCaseIDs returns the distinct case ids records actually ran, in first-seen order.
func executedCaseIDs(records []CaseRecord) []string {
	seen := make(map[string]bool, len(records))
	var ids []string
	for _, r := range records {
		if !seen[r.CaseID] {
			seen[r.CaseID] = true
			ids = append(ids, r.CaseID)
		}
	}
	return ids
}
