"""dist-guard — the no-committed-binaries guard for SC-DISTRIBUTION.

CD, not the git tree, is the distribution channel: a library release pins a git tag with no
archive, a CLI release publishes per-OS/arch archives + checksums to the platform release
(see the release-*.yml workflow templates in .github/workflows/). Nothing built should land
as a tracked git blob. The one standing exception is `allowlist.ENTRIES` — kept to exactly one
entry by construction, documented, and regenerated byte-for-byte by `generate` so it can never
drift from its own source silently.
"""
